CREATE TABLE IF NOT EXISTS users
(
    user_id  BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    email    VARCHAR(255)          NOT NULL,
    login    VARCHAR(255)          NOT NULL,
    name     VARCHAR(60),
    birthday timestamp
);

CREATE TABLE IF NOT EXISTS rating
(
    rating_id INT NOT NULL PRIMARY KEY,
    name      VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS film
(
    film_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(60) NOT NULL,
    description  VARCHAR,
    release_date timestamp,
    duration     INT,
    likes        BIGINT,
    rating_id    VARCHAR(10) NOT NULL REFERENCES rating (rating_id)
);

CREATE TABLE IF NOT EXISTS friend
(
    user_id   BIGINT REFERENCES users (user_id) ON DELETE RESTRICT,
    friend_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    confirmed BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS genre
(
    genre_id INT NOT NULL PRIMARY KEY,
    name     VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genre
(
    genre_id BIGINT REFERENCES genre (genre_id) ON DELETE RESTRICT,
    film_id  BIGINT REFERENCES film (film_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS likes
(
    film_id BIGINT REFERENCES film (film_id) ON DELETE RESTRICT,
    user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE
);