drop table if exists film_genre CASCADE;
drop table if exists film CASCADE;
drop table if exists friend CASCADE;
drop table if exists likes CASCADE;
drop table if exists users CASCADE;
drop table if exists genre CASCADE;
drop table if exists mpa CASCADE;
drop table if exists film_mpa CASCADE;
drop table if exists reviews CASCADE;
drop table if exists review_dislikes CASCADE;
drop table if exists review_likes CASCADE;
drop table if exists feeds CASCADE;


CREATE TABLE IF NOT EXISTS users
(
    user_id  BIGINT AUTO_INCREMENT PRIMARY KEY,
    email    VARCHAR(255) NOT NULL,
    login    VARCHAR(255) NOT NULL,
    name     VARCHAR(60),
    birthday timestamp
);

CREATE TABLE IF NOT EXISTS mpa
(
    mpa_id   BIGINT PRIMARY KEY,
    mpa_name VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS film
(
    film_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(60) NOT NULL,
    description  VARCHAR,
    release_date timestamp,
    duration     INT,
    rate         BIGINT
);

CREATE TABLE IF NOT EXISTS friend
(
    user_id   BIGINT REFERENCES users (user_id) ON DELETE RESTRICT,
    friend_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    confirmed BOOLEAN
);

CREATE TABLE IF NOT EXISTS genre
(
    genre_id   INT PRIMARY KEY,
    genre_name VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS film_genre
(
    genre_id BIGINT REFERENCES genre (genre_id),
    film_id  BIGINT REFERENCES film (film_id)
);

CREATE TABLE IF NOT EXISTS likes
(
    film_id BIGINT REFERENCES film (film_id) ON DELETE RESTRICT,
    user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS film_mpa
(
    film_id BIGINT REFERENCES film (film_id) ON DELETE CASCADE,
    mpa_id  BIGINT REFERENCES mpa (mpa_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reviews
(
    review_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content     VARCHAR(255) NOT NULL,
    is_positive BOOLEAN      NOT NULL,
    user_id     BIGINT       NOT NULL,
    film_id     BIGINT       NOT NULL,
    useful      BIGINT       NOT NULL
);

CREATE TABLE IF NOT EXISTS review_likes
(
    review_id BIGINT REFERENCES reviews (review_id) ON DELETE CASCADE,
    user_id   BIGINT REFERENCES users (user_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS review_dislikes
(
    review_id BIGINT REFERENCES reviews (review_id) ON DELETE CASCADE,
    user_id   BIGINT REFERENCES users (user_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS feeds
(
    timestamp BIGINT       NOT NULL,
    user_id BIGINT         NOT NULL,
    event_type VARCHAR(6)  NOT NULL,
    operation VARCHAR(6)   NOT NULL,
    event_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    entity_id BIGINT       NOT NULL
);